# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Strain.create(name: 'blue-dream')
Strain.create(name: 'sour-diesel')
Strain.create(name: 'og-kush')
Strain.create(name: 'green-crack')
Strain.create(name: 'girl-scout-cookie')
Strain.create(name: 'granddaddy-purple')
Strain.create(name: 'white-widow')
Strain.create(name: 'jack-herer')
Strain.create(name: 'bubba-kush')
Strain.create(name: 'ak-47')
Strain.create(name: 'trainwreck')
Strain.create(name: 'northern-lights')
Strain.create(name: 'blue-cheese')
Strain.create(name: 'headband')
Strain.create(name: 'purple-kush')
Strain.create(name: 'pineapple-express')
Strain.create(name: 'alaskan-thunder-fuck')
Strain.create(name: 'chemdawg')
Strain.create(name: 'blackberry-kush')
Strain.create(name: 'super-silver-haze')
Strain.create(name: 'durban-poison')
Strain.create(name: 'lemon-haze')
Strain.create(name: 'strawberry-cough')
Strain.create(name: 'grape-ape')
Strain.create(name: 'cheese')
Strain.create(name: 'blueberry')
Strain.create(name: 'master-kush')
Strain.create(name: 'super-lemon-haze')
Strain.create(name: 'afghan-kush')
Strain.create(name: 'maui-waui')
Strain.create(name: 'la-confidential')
Strain.create(name: 'amnesia-haze')
Strain.create(name: 'skywalker')
Strain.create(name: 'chocolope')
Strain.create(name: 'cherry-pie')
Strain.create(name: 'purple-urkle')
Strain.create(name: 'g-13')
Strain.create(name: 'gods-gift')
Strain.create(name: 'lemon-kush')
Strain.create(name: '100-og')
Strain.create(name: 'purple-haze')
Strain.create(name: 'bubble-gum')
Strain.create(name: 'nyc-diesel')
Strain.create(name: 'hindu-kush')
Strain.create(name: 'tahoe-og')
Strain.create(name: 'death-star')
Strain.create(name: 'mango-kush')
Strain.create(name: 'skywalker-og')
Strain.create(name: 'cinderella-99')
