# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Region.create(name: 'AL')
Region.create(name: 'AK')
Region.create(name: 'AZ')
Region.create(name: 'AR')
Region.create(name: 'CA')
Region.create(name: 'CO')
Region.create(name: 'CT')
Region.create(name: 'DE')
Region.create(name: 'FL')
Region.create(name: 'GA')
Region.create(name: 'HI')
Region.create(name: 'ID')
Region.create(name: 'IL')
Region.create(name: 'IN')
Region.create(name: 'IA')
Region.create(name: 'KS')
Region.create(name: 'KY')
Region.create(name: 'LA')
Region.create(name: 'ME')
Region.create(name: 'MD')
Region.create(name: 'MA')
Region.create(name: 'MI')
Region.create(name: 'MN')
Region.create(name: 'MS')
Region.create(name: 'MO')
Region.create(name: 'MT')
Region.create(name: 'NE')
Region.create(name: 'NV')
Region.create(name: 'NH')
Region.create(name: 'NJ')
Region.create(name: 'NM')
Region.create(name: 'NY')
Region.create(name: 'NC')
Region.create(name: 'ND')
Region.create(name: 'OH')
Region.create(name: 'OK')
Region.create(name: 'OR')
Region.create(name: 'PA')
Region.create(name: 'RI')
Region.create(name: 'SC')
Region.create(name: 'SD')
Region.create(name: 'TN')
Region.create(name: 'TX')
Region.create(name: 'UT')
Region.create(name: 'VT')
Region.create(name: 'VA')
Region.create(name: 'WA')
Region.create(name: 'WV')
Region.create(name: 'WI')
Region.create(name: 'WY')
